### ISSUE TITLE
"Clean" target on kproj doesn't delete NuGet packages

### ISSUE THREAD

**Issue by Daniel15** [aspnet/XRE#1301] opened 2015-02-28 05:57 UTC
`msbuild blah.kproj` on an ASP.NET Class Library generates .nupkg and .symbols.nupkg files, but `msbuild blah.kproj /t:clean` does not delete these files.

**Comment by BillHiebert** [comment] 2015-03-02 16:01
We currently don't have a clean target at all. There is an item on the backlog to fix this.

**Comment by glennc** [comment] 2015-03-04 23:57
Closing this, the issue is tracked in the tooling repositories.

**Comment by Daniel15** [comment] 2015-03-04 23:58
Thanks! Is there a public issue I can watch or is it only in an internal tracker?

**Closed by glennc** 2015-03-04 23:57 UTC
