### ISSUE TITLE
Console Text Color Persists When 'k web' is stopped via ctrl-c

### ISSUE THREAD

**Issue by ardalis** [aspnet/XRE#863] opened 2014-11-06 19:28 UTC
If an error occurs and is output in red text, and then the WebListener is killed using ctrl-c, the console color remains formatted red.

**Comment by glennc** [comment] 2015-03-05 00:19
Duplicate of issue in the logging repo: https://github.com/aspnet/Logging/issues/46

**Closed by glennc** 2015-03-05 00:19 UTC
