### ISSUE TITLE
When there is a P2P reference to a project that doesn't build we should get a build error

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/XRE#1323] opened 2015-03-05 23:44 UTC
Consider this scenario.

MyWebProject (ASP.NET 5 web project) references MySharedProject (ASP.NET 5 class library). If there is a compile error in MySharedProject when you execute ```kpm biuld``` on ```MyWebProject``` we should get a build error that ```MySharedProject``` doesn't build. Instead we get ``build succeeded```.

cc @davidfowl @danroth27 @glennc @BillHiebert @barrytang

**Comment by davidfowl** [comment] 2015-03-06 08:57
Dupe of  https://github.com/aspnet/XRE/issues/583

**Closed by davidfowl** 2015-03-06 08:57 UTC
